<?php

/**
 * Created by Jorge P. Hernandez Lalcebo
 * Mail: j.lalcebo@chargebacks911.com
 * Date: 11/18/20 3:10 PM
 */

declare(strict_types=1);

namespace GTMC\Aws\Parameters\Athena\Actions;

use GTMC\Aws\Parameters\Parameter;

/**
 * Provides a list of available query IDs only for queries saved in the specified workgroup. Requires that
 * you have access to the specified workgroup. If a workgroup is not specified, lists the saved queries
 * for the primary workgroup.
 *
 * @package GTMC\Aws\Parameters\Athena\Actions
 * @see https://docs.aws.amazon.com/athena/latest/APIReference/API_ListNamedQueries.html
 */
class ListNamedQueries extends Parameter
{
    /**
     * The maximum number of queries to return in this request.
     *
     *   Valid Range: Minimum value of 0. Maximum value of 50.
     *
     * @var int
     */
    public $maxResults;

    /**
     * A token generated by the Athena service that specifies where to continue pagination if a previous
     * request was truncated. To obtain the next set of pages, pass in the NextToken from the response
     * object of the previous page call.
     *
     *   Length Constraints: Minimum length of 1. Maximum length of 1024.
     *
     * @var string
     */
    public $nextToken;

    /**
     * The name of the workgroup from which the named queries are being returned. If a workgroup is not
     * specified, the saved queries for the primary workgroup are returned.
     *
     *   Pattern: [a-zA-Z0-9._-]{1,128}
     *
     * @var string
     */
    public $workGroup;

    /**
     * @param  int|null  $maxResults  The maximum number of queries to return in this request.
     * @param  string|null  $nextToken  A token generated by the Athena service that specifies where to continue
     * pagination if a previous request was truncated. To obtain the next set of pages, pass in the NextToken
     * from the response object of the previous page call.
     * @param  string|null  $workGroup  The name of the workgroup from which the named queries are being returned.
     * If a workgroup is not specified, the saved queries for the primary workgroup are returned.
     */
    public function __construct(int $maxResults = null, string $nextToken = null, string $workGroup = null)
    {
        $this->maxResults = $maxResults;
        $this->nextToken = $nextToken;
        $this->workGroup = $workGroup;
    }
}
