<?php

/**
 * Created by Jorge P. Hernandez Lalcebo
 * Mail: j.lalcebo@chargebacks911.com
 * Date: 11/18/20 3:21 PM
 */

declare(strict_types=1);

namespace GTMC\Aws\Parameters\Athena\Actions;

use GTMC\Aws\Parameters\Parameter;

/**
 * Lists the metadata for the tables in the specified data catalog database.
 *
 * @package GTMC\Aws\Parameters\Athena\Actions
 * @see https://docs.aws.amazon.com/athena/latest/APIReference/API_ListTableMetadata.html
 */
class ListTableMetadata extends Parameter
{
    /**
     * The name of the data catalog for which table metadata should be returned.
     *
     *   Length Constraints: Minimum length of 1. Maximum length of 256.
     *   Pattern: [\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\t]*
     *
     * @var string
     */
    public $catalogName;

    /**
     * The name of the database for which table metadata should be returned.
     *
     *   Length Constraints: Minimum length of 1. Maximum length of 128.
     *
     * @var string
     */
    public $databaseName;

    /**
     * A regex filter that pattern-matches table names. If no expression is supplied,
     * metadata for all tables are listed.
     *
     *   Length Constraints: Minimum length of 0. Maximum length of 256.
     *
     * @var string
     */
    public $expression;

    /**
     * Specifies the maximum number of results to return.
     *
     *   Valid Range: Minimum value of 1. Maximum value of 50.
     *
     * @var int
     */
    public $maxResults;

    /**
     * A token generated by the Athena service that specifies where to continue pagination if a previous
     * request was truncated. To obtain the next set of pages, pass in the NextToken from the response
     * object of the previous page call.
     *
     *   Length Constraints: Minimum length of 1. Maximum length of 1024.
     *
     * @var string
     */
    public $nextToken;

    /**
     * @param  string  $catalogName The name of the data catalog for which table metadata should be returned.
     * @param  string  $databaseName The name of the database for which table metadata should be returned.
     * @param  string|null  $expression A regex filter that pattern-matches table names. If no expression is
     * supplied, metadata for all tables are listed.
     * @param  int|null  $maxResults Specifies the maximum number of results to return.
     * @param  string|null  $nextToken A token generated by the Athena service that specifies where to continue
     * pagination if a previous request was truncated. To obtain the next set of pages, pass in the NextToken
     * from the response object of the previous page call.
     */
    public function __construct(
        string $catalogName,
        string $databaseName,
        string $expression = null,
        int $maxResults = null,
        string $nextToken = null
    ) {
        $this->catalogName = $catalogName;
        $this->databaseName = $databaseName;
        $this->expression = $expression;
        $this->maxResults = $maxResults;
        $this->nextToken = $nextToken;
    }
}
