<?php

/**
 * Created by Jorge P. Hernandez Lalcebo
 * Mail: j.lalcebo@chargebacks911.com
 * Date: 11/16/20 2:05 PM
 */

declare(strict_types=1);

namespace GTMC\Aws\Parameters\Athena\Actions;

use GTMC\Aws\Parameters\Parameter;

/**
 * Lists the data catalogs in the current AWS account.
 *
 * @package GTMC\Aws\ListMap\Athena\Actions
 * @see https://docs.aws.amazon.com/athena/latest/APIReference/API_ListDataCatalogs.html
 */
class ListDataCatalogs extends Parameter
{
    /**
     * Specifies the maximum number of data catalogs to return.
     *
     *   Constraints: Minimum value of 2. Maximum value of 50
     *
     * @var int
     */
    public $maxResult;

    /**
     * A token generated by the Athena service that specifies where to continue pagination
     * if a previous request was truncated. To obtain the next set of pages, pass in the
     * NextToken from the response object of the previous page call.
     *
     *   Constraints: Minimum length of 1. Maximum length of 1024.
     *
     * @var string
     */
    public $nextToken;

    /**
     * @param  int|null  $maxResult  Specifies the maximum number of data catalogs to return.
     * @param  string|null  $nextToken  A token generated by the Athena service that specifies where to continue
     * pagination if a previous request was truncated. To obtain the next set of pages, pass in the NextToken
     * from the response object of the previous page call.
     */
    public function __construct(int $maxResult = null, string $nextToken = '')
    {
        $this->maxResult = $maxResult;
        $this->nextToken = $nextToken;
    }
}
