<?php

/**
 * Created by Jorge P. Hernandez Lalcebo
 * Mail: j.lalcebo@chargebacks911.com
 * Date: 11/18/20 3:35 PM
 */

declare(strict_types=1);

namespace GTMC\Aws\Parameters\Athena\Actions;

use GTMC\Aws\Parameters\Parameter;

/**
 * Lists available workgroups for the account.
 *
 * @package GTMC\Aws\Parameters\Athena\Actions
 * @see https://docs.aws.amazon.com/athena/latest/APIReference/API_ListWorkGroups.html
 */
class ListWorkGroups extends Parameter
{
    /**
     * The maximum number of workgroups to return in this request.
     *
     *   Valid Range: Minimum value of 1. Maximum value of 50.
     *
     * @var int
     */
    public $maxResults;

    /**
     * A token generated by the Athena service that specifies where to continue pagination if a previous
     * request was truncated. To obtain the next set of pages, pass in the NextToken from the response
     * object of the previous page call.
     *
     *   Length Constraints: Minimum length of 1. Maximum length of 1024.
     *
     * @var string
     */
    public $nextToken;

    /**
     * @param  int|null  $maxResults The maximum number of workgroups to return in this request.
     * @param  string|null  $nextToken A token generated by the Athena service that specifies where
     * to continue pagination if a previous request was truncated. To obtain the next set of pages,
     * pass in the NextToken from the response object of the previous page call.
     */
    public function __construct(int $maxResults = null, string $nextToken = null)
    {
        $this->maxResults = $maxResults;
        $this->nextToken = $nextToken;
    }
}
